### ISSUE TITLE
URL download is broken - Unknown . cmd

### ISSUE THREAD

**Issue by arsaboo** [Liupold/fmdpy#14]
Entering the URL returns `Unknown . cmd`
```
fmdpy (v0.6.3)-> https://www.jiosaavn.com/album/XYZ
Unknown . cmd: https://www.jiosaavn.com/album/XYZ
```

**Comment by Liupold** [comment]
Yes yes. cf59fadcfc27f1252370b51ebdbb0b98d7f2dd7a should fix this. Please try again.

**Comment by arsaboo** [comment]
Looks like I need to be more patient :)

**Comment by Liupold** [comment]
You can give it a thorough test now. I am all done for today.
