### ISSUE TITLE
is it OK for these to be public?

### ISSUE THREAD

**Issue by JaDogg** [Liupold/fmdpy#2]
https://github.com/Liupold/fmdpy/blob/ac38dae23e9955722aa79a30e6208524ea8efa1c/fmdpy/splist.py#L35

**Comment by Liupold** [comment]
I guess. Any better solutions possible ?

**Comment by JaDogg** [comment]
I'd just revoke these API keys and keep it as it is, tell people to update it with their own `client_id/client_secret` in README.

**Comment by Liupold** [comment]
This would require an configuration file (global variables can be used but not ideal).  And I do wanted to have configuration file for this project. The `.ini` structure is good. Feel free to contribute. I am not sure when can I implement this as it's not a priority rn for me.

**Comment by Liupold** [comment]
This are no longer public. Closing.
