### ISSUE TITLE
Accept URL as input

### ISSUE THREAD

**Issue by arsaboo** [Liupold/fmdpy#7]
Instead of searching, I was wondering if we can add a feature to directly provide a URL. The search is not perfect.

**Comment by Liupold** [comment]
Yes, this would be great!

**Comment by Liupold** [comment]
Or maybe we can detect the URL using regex. If the search is a valid URL then just download / use that.

**Comment by arsaboo** [comment]
Even better...love that. Would you take a look at implementing this? I looked at the code but am a little lost. I am assuming, we parse "`prompt_input` to check if it is a valid URL. Not sure which function to pass the URL to.

**Comment by Liupold** [comment]
Here is the variable which contains the initial search https://github.com/Liupold/fmdpy/blob/2eacc8209e4151bde341613bf9fcbb38530d3f9e/fmdpy/__main__.py#L106

I would suggest you hook url from there. BTW if you are willing to work with prompt I would suggest to rewrite. (It's Buggy at best).

Here is where the song object is created.
(You need to extract the song id somehow). [Look into jiosavan APIs available in github ]
https://github.com/Liupold/fmdpy/blob/2eacc8209e4151bde341613bf9fcbb38530d3f9e/fmdpy/api.py#L20

Sorry, I have a lot of things going on now, will love to work on this ASAP. Can't promise a deadline though.

**Comment by arsaboo** [comment]
I tried looking into it, but could not make much progress. I think [python-jiosaavn](https://github.com/abhichaudharii/jiosaavn-python) can provide the `song_id`. I created [this branch](https://github.com/arsaboo/fmdpy/tree/pass_url) to get the song_id and then pass it. However, I am unable to get past the input. I added additional logging, but none of those are printed. If I pass a URL, I keep getting this error:

```
$ fmdpy --fmt mp3 -c 25 https://www.jiosaavn.com/song/naiyo-lagda/Mh0eZBVRBwQ
1) https://youtu.be/00jSk2y5sJY [Shashi Prakas] (2022)

fmdpy: https://www.jiosaavn.com/song/naiyo-lagda/Mh0eZBVRBwQ
Traceback (most recent call last):
  File "/home/arsaboo/.local/bin/fmdpy", line 8, in <module>
    sys.exit(fmdpy())
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/fmdpy/__main__.py", line 121, in fmdpy
    c_pool += [*range(int(lower) - 1, int(upper))]
ValueError: invalid literal for int() with base 10: 'https'
```

If you can help me getting past this, I may be able to complete the rest of it.

**Comment by arsaboo** [comment]
BTW, I am not sure where does `https://youtu.be/00jSk2y5sJY [Shashi Prakas] (2022)` come from

**Comment by arsaboo** [comment]
I am trying to install/upgrade using the command `python3 -m pip install git+https://github.com/arsaboo/fmdpy@pass_url`, but it looks like the changes are not reflected. Not sure what I am missing.

**Comment by Liupold** [comment]
urls are now supported, try 

`
fmdpy "YOUR URL HERE"
`

**Comment by Liupold** [comment]
I am not publishing it yet. I was thinking of adding URL  fetching from  JioSavan directly.

**Comment by Liupold** [comment]
Try it out and verify that it's working. I will fix the prompt before releasing. And Will implement the folder feature requested (no promises).

**Comment by Liupold** [comment]
Directory management is also added.  (It wasn't as difficult as i thought it would be). Anyways do try them out. After that i will create a release.

**Comment by arsaboo** [comment]
This is great. Works very well. This is a much better way of doing things than what I was [trying](https://github.com/arsaboo/fmdpy/tree/pass_url).  Appreciate the cleanup as well. Closing the issue now...

**Comment by Liupold** [comment]
Just for the record, Album URLs are also supported.
