### ISSUE TITLE
fmt = mp3 not working

### ISSUE THREAD

**Issue by arsaboo** [Liupold/fmdpy#9]
On one of my machines, `fmt --mp3` (both using the command line parameters or the config file) is not working. If I keep `fmt = native`, I get an mp4 file. However, no output is produced when I use `fmt = mp3`. I reinstalled FFmpeg and even manually tried the conversion (which works). 

Any thoughts on how I may debug this?

**Comment by Liupold** [comment]
Here is where the conversion happen,           https://github.com/Liupold/fmdpy/blob/571984fc3ab66e3bda963f638ba8bc08c7725bb5/fmdpy/download.py#L76

Make sure ffmpeg module is working correctly.
Try: `fmdpy -u`

**Comment by arsaboo** [comment]
`fmdpy` is on the latest version. 
```
$ fmdpy -v
fmdpy: 0.6.1 (/usr/bin/python3)
```
Unfortunately, there is no error message. There is a progress bar but no output is produced. I tried changing the `loglevel` to verbose in the `download`, but no additional output was produced. Is it possible to specify a log file for FFmpeg conversion?

**Comment by Liupold** [comment]
specify the directory. The default behavior is now a bit different and files are stored in ~/Music by default. 

I don't really know a lot of that module. You can look into ffmpeg module documentation.

**Comment by Liupold** [comment]
I made this so new users don't have to chance the filepath to enjoy the folder management system.

**Comment by arsaboo** [comment]
I have specified the directory `default_directory = /home/arsaboo/shared/music/$album`

I will look into ffmpeg

**Comment by Liupold** [comment]
Oh, In that case, it's probably ffmpeg module. Is the output filename with extension correct?

**Comment by arsaboo** [comment]
What do you mean? There is no output file that is created if I specify `fmt = mp3`.

**Comment by arsaboo** [comment]
BTW...why is the default output mp4? Since we are dealing with audio, shouldn't mp3 be the default output?

**Comment by arsaboo** [comment]
Ok...so, I changed the output to `mp3` and I am getting an mp3 output 
https://github.com/Liupold/fmdpy/blob/571984fc3ab66e3bda963f638ba8bc08c7725bb5/fmdpy/download.py#L87

**Comment by Liupold** [comment]
The native container used by JioSavan is .mp4, changing .mp4 to .mp3 only changes the filename not the data format.

**Comment by Liupold** [comment]
I just tested it. It's working for me. I would also like to point out that the GitHub Actions has a test where the conversion is checked which is working for Linux, Windows, Mac. I would suggest you test the `ffmpeg-python` module, Write a small python script which does the conversion and go from there. This might be of interest https://github.com/kkroening/ffmpeg-python/issues/22

**Comment by arsaboo** [comment]
OK...will close this for now. Will try to figure out how to add additional logging.

**Comment by Liupold** [comment]
Thank you. If you do add logger support. Please create a pull request.
